{"description": "THE COLOURS OF THE SEASON. When you lace up the Chuck Taylor All Star low top sneakers, you\u2019re agreeing to start your season with a bang. These canvas sneakers feature the iconic style you know and love with bold new color updates to bring added flair to your spring wardrobe. Style them up and step out.", "name": "Chuck Taylor All Star Seasonal Low Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "THE FUN COLOURS OF SUMMER. The Chuck Taylor All Star Madison colour Pop Mesh sneaker is a burst of summer fun. It starts with durable canvas upper that\u2019s boldly colourful, ready to make a splash no matter the outfit you wear. Inside, the OrthoLite insole for cushioning brings comfort along for the ride every step of the way. Lace them up and strut into summer.", "name": "Chuck Taylor All Star Perforated Star Madison Low Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "Scaled back in size for the next generation of original thinkers, rockers and artists, this Converse Chuck Taylor All Star remains true to the iconic original with classic details on a comfortable canvas upper.", "name": "Chuck Taylor All Star Low Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "BACK TO SCHOOL TONES. Back to school gets a brand new vibe with the Chuck Taylor All Star 2V low top sneaker. These fun kicks show off your kid\u2019s personality with a durable canvas upper, non-marking rubber outsole and aluminum eyelet accents. To help with getting ready, these sneakers are made with a heel loop assist and two hook and loop closures for easy on and off. With a padded tongue and collar and Smart Foam with canvas lining, your child can get their learn on instead of worrying about comfort.", "name": "Chuck Taylor All Star 2V Fall Uniform Low Top Infant/Toddler", "price": "CAD $40.00"}
{"description": "FOR THE DREAMERS. Inspired by the beauty of imagination, the Chuck Taylor All Star Fairy Dust sneaker is bringing back the magic and a little extra shimmer. With a glam textile upper and metallic heel stay, these dreamy high top kicks are sure to get some \u201coohs\u201d and \u201cahhs.\u201d The non-marking rubber outsole, debossed medial patch, medial eyelets and Smart Foam liner all bring style and comfort, too.", "name": "Chuck Taylor All Star Fairy Dust High Top Little/Big Kids", "price": "CAD $55.00"}
{"description": "FOR THE DREAMERS. Inspired by the beauty of imagination, the Chuck Taylor All Star Fairy Dust sneaker is bringing back the magic and a little extra shimmer. With a glam textile upper and metallic heel stay, these dreamy high top kicks are sure to get some \u201coohs\u201d and \u201cahhs.\u201d The non-marking rubber outsole, medial eyelets and Smart Foam liner all bring style and comfort, too.", "name": "Chuck Taylor All Star Fairy Dust Low Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "EASY GOING SPARKLES. Give your little one something to glow about with the Chuck Taylor All Star 2V sneaker. With a shiny-coated glitter upper, non-marking rubber outsole and woven tongue label, these kicks already make a big statement on little feet. Plus, they\u2019ve got a Smart Foam with canvas liner, two hook and loop closures and a heel loop assist for easy on and off on even the busiest of days. Just pull them on and she\u2019s off in a trail of sparkles.", "name": "Chuck Taylor All Star 2V Autumn Glitter Low Top Infant/Toddler", "price": "CAD $50.00"}
{"description": "COOL ENOUGH FOR SCHOOL. When you\u2019re thinking about what your kid needs for back to school, the Chuck Taylor All Star Street has got to make the list. A fashion essential, these comfortable kicks feature the fall\u2019s best colours, an elastic gore tongue for easy on and off, and a non-marking rubber outsole for traction. With small touches like a Smart Foam with canvas sockliner and medial eyelets for airflow, these are the sneakers that can stand up to even the longest of school days.", "name": "Chuck Taylor All Star Street Slip Fall Uniform Little/Big Kids", "price": "CAD $50.00"}
{"description": "COOL ENOUGH FOR SCHOOL. When you\u2019re thinking about what your kid needs for back to school, the Chuck Taylor All Star Street has got to make the list. A fashion essential, these comfortable kicks feature the fall\u2019s best colours, an elastic gore tongue for easy on and off, and a non-marking rubber outsole for traction. With small touches like a screen-printed medial patch, a Smart Foam with canvas sockliner, and aluminum eyelets, these are the sneakers that can stand up to even the longest of school days.", "name": "Chuck Taylor All Star Street Slip Fall Uniform Infant/Toddler", "price": "CAD $45.00"}
{"description": "INSPIRED BY THE WORLD. Inspired by countries from all over the world, this collection of One Star sneakers is all about coming together in celebration. Each unique sneaker features a canvas upper with suede eyerow details, an EVA insole for cushioning, and our embroidered One Star logo. Pick the colours that speak to you and wear them proudly.", "name": "One Star Country Pride Low Top Little/Big Kids", "price": "CAD $55.00"}
{"description": "ESSENTIAL COMFORT. The Converse Essentials Sportswear Crew Men's Sweatshirt is made with warm French terry fabric for exceptional warmth wherever you go.", "name": "Men's Essentials Crew", "price": "CAD $80.00"}
{"description": "A BACK TO SCHOOL ESSENTIAL. If you feel a surge of confidence when you put on the Chuck Taylor All Star Madison low top sneaker, it\u2019s because they\u2019re designed to maximize your awesomeness. These kicks feature elastic goring for easy on and off and vivid seasonal colours. But don\u2019t forget, comfort is still key with a padded collar and tongue, non-marking rubber outsole, and an OrthoLite\u00ae insole for cushioning. So carry on.", "name": "Chuck Taylor All Star Madison Fall Uniform Low Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "STAND TALL IN ALL-OVER POLKA DOT STYLE", "name": "One Star Polka Dot Platform Low Top", "price": "CAD $110.00"}
{"description": "CRISP POLKA DOT STYLE. We\u2019re doing dots in a brand new way with the Chuck Taylor All Star sneaker. These crisp, clean polka dots in totally unexpected ways\u2014across the durable canvas upper and sprinkled over the midsole. The OrthoLite insole for cushioning helps to keep you comfortable so you can rock your edgy look all day long. Go for dots that break outside the box and keep things funky, no matter what you pair them with.", "name": "Chuck Taylor All Star Polka Dots Low Top", "price": "CAD $70.00"}
{"description": "THE ROAR OF GIRL POWER. Nothing beats a healthy dose of girl power and the Chuck Taylor All Star Lift Clean is adding to the vibe. These super dope kicks are inspired by the girl bands of the \u201890s and \u201800s who rocked classic looks all while rocking the stage. With a premium leather upper, elevated classic rubber outsole and EVA insole for cushioning, these sneakers are made to help you kick things up a notch whenever you lace them up.", "name": "Chuck Taylor All Star Lift Leather High Top", "price": "CAD $100.00"}
{"description": "THE ROAR OF GIRL POWER. Nothing beats a healthy dose of girl power and the Chuck Taylor All Star Lift Clean is adding to the vibe. These super dope kicks are inspired by the girl bands of the \u201890s and \u201800s who rocked classic looks all while rocking the stage. With a premium leather upper, elevated classic rubber outsole and EVA insole for cushioning, these sneakers are made to help you kick things up a notch whenever you lace them up.", "name": "Chuck Taylor All Star Lift Leather Low Top", "price": "CAD $95.00"}
{"description": "INSPIRED BY SUMMER SUNSETS. Hot summer days call for light materials and sun-washed colours. These Chuck Taylor All Star high top kicks are bringing the nostalgia of summer sunsets on the beach with an ombre-washed graphic and lightweight textile upper. With a classic rubber outsole and OrthoLite\u00ae insole for cushioning, it\u2019s the next best thing to being barefoot on the beach.", "name": "Chuck Taylor All Star Ombre Wash High Top", "price": "CAD $75.00"}
{"description": "INSPIRED BY SUMMER SUNSETS. Hot summer days call for light materials and sun-washed colours. These Chuck Taylor All Star low top kicks are bringing the nostalgia of summer sunsets on the beach with an ombre-washed graphic and lightweight textile upper. With a classic rubber outsole and OrthoLite\u00ae insole for cushioning, it\u2019s the next best thing to being barefoot on the beach.", "name": "Chuck Taylor All Star Ombre Wash Low Top", "price": "CAD $70.00"}
{"description": "THE CHUCK 70 PARKWAY FLORAL. A rogue florist takes over the Chuck 70, so you can bring a breath of fresh air to the concrete jungle. These sleek kicks feature a leather upper, accented by embroidered floral detail for a wild, colourful look. With an OrthoLite\u00ae insole for cushioning, these comfy sneakers bring a breath of fresh air to city life with a bold new look.", "name": "Chuck 70 Parkway Floral Low Top", "price": "CAD $120.00"}
{"description": "STAND UP AND STAND OUT. Ready to bring the noise, ladies? Start with our show-stopping One Star sneaker. Made for those who are bold enough to stand out, these premium suede sneakers feature a dazzling metallic finish for a fashion-forward look. These kicks may look fun, but every sneaker\u2019s got a tough side. With a durable heel tab and OrthoLite\u00ae insole for cushioning, these sneakers are ready to take on the day and keep you comfortable while doing it. Now who\u2019s with us?", "name": "One Star Precious Metal Suede Low Top", "price": "CAD $100.00"}
{"description": "MAKE IT POP WITH METALLICS. Say hello to your new favorite sneaker, the dazzling One Star Platform sneaker. These kicks feature a lovely stacked midsole for extra height, but the distinguishing details don\u2019t stop there. The premium suede upper has a flashy metallic finish, perfect for taking your personal style to the next level. Inside, the EVA insole for cushioning keeps you comfortable, so you can strut your stuff all day long.", "name": "One Star Platform Precious Metal Suede Low Top", "price": "CAD $120.00"}
{"description": "NATURE MEETS CITY. Artists take their inspiration from the city, and these Chuck Taylor All Star sneakers are bringing a breath of fresh of air to the concrete jungle. With a bold, linear floral print these classic high top sneakers are art imitating life, inspired by rogue florists who leave beautiful arrangements on city street corners. With a classic rubber outsole for comfort and an OrthoLite insole for cushioning, these sneakers will breathe new life into your look.", "name": "Chuck Taylor All Star Linear Floral Low Top", "price": "CAD $70.00"}
{"description": "NATURE MEETS CITY. Artists take their inspiration from the city, and these Chuck Taylor All Star sneakers are bringing a breath of fresh of air to the concrete jungle. With a bold, linear floral print these classic high top sneakers are art imitating life, inspired by rogue florists who leave beautiful arrangements on city street corners. With a classic rubber outsole for comfort and an OrthoLite insole for cushioning, these sneakers will breathe new life into your look.", "name": "Chuck Taylor All Star Linear Floral High Top", "price": "CAD $75.00"}
{"description": "EYE-CATCHING SMOKE PRINT", "name": "Women's Smoke Print Long Sleeve Dress", "price": "CAD $90.00"}
{"description": "RELAXED SPARKLE", "name": "Women's Metallic Chuck Patch T-Shirt", "price": "CAD $40.00"}
{"description": "ENGINEERED FOR COMFORT. The Converse Engineered Jacquard Legging is about three key attributes\u2014comfort, optimal fit and outfitting. It gets the job done in the most fashionable way with a comfortable double layer waistband, minimal seams and our Wordmark logo down the leg. It maintains a sleek silhouette while bringing the details that matter in a cozy, durable legging.", "name": "Women's Engineered Jacquard Leggings", "price": "CAD $85.00"}
{"description": "ESSENTIAL OVERSIZED HOODIE", "name": "Women's Essentials Oversized Pullover Hoodie", "price": "CAD $80.00"}
{"description": "SOFT COMFORT.  The\u00a0Converse Essentials Cropped Women's\u00a0Hoodie is made with soft cotton in a cropped silhouette for breathable comfort.", "name": "Women's Essentials Cropped Hoodie", "price": "CAD $80.00"}
{"description": "ESSENTIAL METALLIC STAR HOODIE", "name": "Women's Essentials Metallic Star Chevron Oversized Pullover Hoodie", "price": "CAD $85.00"}
{"description": "SOFT, COTTON COMFORT.", "name": "Women's Clear Foil Chuck Patch Crew T-Shirt", "price": "CAD $30.00"}
{"description": "COMFY CROPPED CREW", "name": "Women's Star Chevron Track Cropped Crew Sweatshirt", "price": "CAD $85.00"}
{"description": "PACKABLE, ON-THE-GO STYLE.", "name": "Women's Feather Print Blur 2.0 Jacket", "price": "CAD $120.00"}
{"description": "TRADITIONAL LOOK. MAXIMUM COMFORT. The Converse Star Chevron Track Short is made to look like the classic with the added comfort of a tricot construction. It\u2019s got all of the cozy extras you could ever need like a fold over waistband, interior draw cord and zipper pockets in front and back. The classic fit silhouette and woven trim make these shorts a fashionable stable for any summer wardrobe.", "name": "Women's Star Chevron Track Short", "price": "CAD $60.00"}
{"description": "TRACK ZIP FOR HER. The traditional track zip silhouette gets a feminine update with the Converse Star Chevron Track Jacket, made with a soft tricot construction. Take a close look and check out the details like woven trim tape on the sleeves, front slant zippered pockets and classic feminine fit. Zip it up to add some edge to your look.", "name": "Women's Star Chevron Track Jacket", "price": "CAD $100.00"}
{"description": "FOR THE DREAMERS. Inspired by the beauty of imagination, the Chuck Taylor All Star Fairy Dust 2V sneaker is bringing back the magic and a little extra shimmer. With a glam textile upper and metallic heel stay, these dreamy kicks are sure to get some \u201coohs\u201d and \u201cahhs.\u201d The non-marking rubber outsole and woven tongue label also bring their own flair. The best part? The heel loop assist and double hook-and-loop closure for easy on and easy off, so your little one can get back to dreaming.", "name": "Chuck Taylor All Star 2V Fairy Dust Low Top Infant/Toddler", "price": "CAD $45.00"}
{"description": "The Converse All Star Chuck \u201970 is our re-crafted sneaker that uses modern details to celebrate the original Chuck Taylor All Star from the 1970's. It features a slightly higher rubber foxing, a cushioned footbed that provides long-lasting comfort and a more substantial rubber toe cap. Additional vintage details include stitching on the sidewall and a heavier-grade canvas upper for comfort and durability. It\u2019s an authentic throwback look that retains the iconic Chuck Taylor attributes you know and love, like the star-centered heel patch and vulcanized rubber outsole.", "name": "Chuck 70 Low Top", "price": "CAD $85.00"}
{"description": "The Converse All Star Chuck \u201970 is our re-crafted sneaker that uses modern details to celebrate the original Chuck Taylor All Star from the 1970's. It features a slightly higher rubber foxing, a cushioned footbed that provides long-lasting comfort and a more substantial rubber toe cap. Additional vintage details include stitching on the sidewall and a heavier-grade canvas upper for comfort and durability. It\u2019s an authentic throwback look that retains the iconic Chuck Taylor attributes you know and love, like the star-centered ankle patch and vulcanized rubber outsole.", "name": "Chuck 70 High Top", "price": "CAD $90.00"}
{"description": "PALM EMBROIDERED V-NECK T-SHIRT", "name": "Women's Palm Embroidered V-Neck T-Shirt", "price": "CAD $35.00"}
{"description": "CHUCK REMEMBERS THE SUMMER OF LOVE", "name": "Chuck 70 Tie Dye High Top", "price": "CAD $90.00"}
{"description": "INSPIRED BY THE WORLD. Inspired by countries from all over the world, this collection of One Star sneakers is all about coming together in celebration. Each unique sneaker features a canvas upper with suede eyerow details, an EVA insole for cushioning, and our embroidered One Star logo. Pick the colours that speak to you and wear them proudly.", "name": "One Star Country Pride Low Top", "price": "CAD $90.00"}
{"description": "90s STREET MEETS SPORT INFLUENCE. The 90s never go out of style and that\u2019s why we\u2019ve mixed some of its classic elements into one awesome throwback sneaker. The Chuck Taylor All Star 70 blends  the edgy street look with the funky colours and sport influence of the 90s. These sneakers feature a 3-colour pinstripe design, varnished midsole and an OrthoLite insole for cushioning. So you can feel great and look bright as you two-step through summer, one 90s track at a time.", "name": "Chuck 70 Canvas Brights Low Top", "price": "CAD $85.00"}
{"description": "RICH TONES. ICONIC SILHOUETTE. It\u2019s true\u2014a classic only gets better with time, and there\u2019s no better example than the Chuck Taylor All Star high top. Featuring colour updates perfect for spring, these canvas sneakers are all about earthy neutrals and rich shades. This iconic sneaker is enhanced by the OrthoLite insole for cushioning, so you can rock your personal style in complete comfort.", "name": "Chuck Taylor All Star Seasonal High Top", "price": "CAD $70.00"}
{"description": "Edgy, bold and glittery all over.", "name": "Converse x Miley Cyrus Chuck Taylor All Star Low Top", "price": "CAD $85.00"}
{"description": "TIMELESS TIE-DYE FUN. Summer is the perfect time to rock tie-dye, so we\u2019re bringing it back to grace the Chuck Taylor All Star 70 sneakers. Our breathable canvas upper is perfect for a 2-colour tie-dye refresh, complete with a vulcanized rubber sole and an OrthoLite insole for cushioning. It\u2019s a timeless look that is all about expressing your personal style. Show off your personality and head out for some summer fun.", "name": "Chuck 70 Tie Dye Low Top", "price": "CAD $85.00"}
{"description": "THE ICON, REBUILT TO SKATE.", "name": "CTAS Pro Perforated Suede High Top", "price": "CAD $90.00"}
{"description": "THE ICON, REBUILT TO SKATE.", "name": "CTAS Pro Perforated Suede Low Top", "price": "CAD $85.00"}
{"description": "CLASSIC CHUCK. PLUSH NEW TEXTURE.", "name": "Chuck Taylor All Star Terry High Top", "price": "CAD $80.00"}
{"description": "LEGENDARY STREET STYLE. FRESH SEASONAL COLOURS.", "name": "One Star Premium Suede Low Top", "price": "CAD $100.00"}
{"description": "LEGENDARY STREET STYLE. FRESH SEASONAL COLOURS.", "name": "One Star Premium Suede Mid", "price": "CAD $105.00"}
{"description": "CLASSIC CHUCK. PLUSH NEW TEXTURE.", "name": "Chuck Taylor All Star Terry Low Top", "price": "CAD $75.00"}
{"description": "Jonathan Anderson is a British-based designer at the forefront of the international fashion scene. His collaborative collection with Converse, inspired by the friction of clashing ideas, brings high-end appeal to street-bound style. For his latest release with Converse, Anderson continues to explore the space between contrasting aesthetics and deconstructed textiles. Mashing up classic brogue shoe detailing, inverted suede, patchwork denim, and\u2014for the first time ever the Chuck 70 XX High silhouette\u2014the Simply_Complex pack examines the beauty between process and perfection.", "name": "Converse x JW Anderson Thunderbolt Suede Low Top", "price": "CAD $200.00"}
{"description": "Jonathan Anderson is a British-based designer at the forefront of the international fashion scene. His collaborative collection with Converse, inspired by the friction of clashing ideas, brings high-end appeal to street-bound style. For his latest release with Converse, Anderson continues to explore the space between contrasting aesthetics and deconstructed textiles. Mashing up classic brogue shoe detailing, inverted suede, patchwork denim, and\u2014for the first time ever the Chuck 70 XX High silhouette\u2014the Simply_Complex pack examines the beauty between process and perfection.", "name": "Converse x JW Anderson Thunderbolt Denim Low Top", "price": "CAD $180.00"}
{"description": "70s LOOK MEETS BOLD GRAPHICS. Inspired by off court prep wear, the Chuck Taylor All Star Deck Star is an edgy take on a classic. The breathable chambray upper features bold graphics for the perfect mix between 70s flair and sophisticated street style. The vulcanized rubber sole creates great traction while the OrthoLite insole for cushioning keeps things comfortable. Slip them on and enjoy the style.", "name": "Chuck Taylor Deck Star 67 Slip", "price": "CAD $90.00"}
{"description": "RICH TONES. ICONIC SILHOUETTE. It\u2019s true\u2014a classic only gets better with time, and there\u2019s no better example than the Chuck Taylor All Star low top. Featuring colour updates perfect for spring, these canvas sneakers are all about earthy neutrals and rich shades. This iconic sneaker is enhanced by the OrthoLite insole for cushioning, so you can rock your personal style in complete comfort.", "name": "Chuck Taylor All Star Seasonal Low Top", "price": "CAD $65.00"}
{"description": "The Converse Chuck Taylor All Star Leather sneaker adds a rich, textured leather upper onto the world\u2019s most iconic high top. The classic star-centered ankle patch, vulcanized rubber sole, brushed metal eyelets, reinforced rubber toe cap, padded footbed and cultural authenticity remain intact.", "name": "Chuck Taylor All Star Leather High Top", "price": "CAD $90.00"}
{"description": "PINSTRIPES FOR PERSONALITY. Fun graphics meet casual style in the Chuck Taylor All Star Shoreline Sneaker. The durable canvas upper features a subtly fun pinstripe graphic to add a hint of detail to your outfit of the day. When it comes to comfort, these kicks are all about it. With a slip-on construction, fixed laces, and an OrthoLite insole for cushioning, you\u2019ll be in cruise control all day long.", "name": "Chuck Taylor All Star Shoreline Prep Style Low Top", "price": "CAD $65.00"}
{"description": "The Converse Chuck Taylor All Star Mono Leather sneaker adds a rich, textured leather upper to the world's most iconic shoe. The vulcanized rubber sole, brushed metal eyelets, reinforced rubber toe cap, padded footbed and cultural authenticity remain intact.", "name": "Chuck Taylor All Star Mono Leather Low Top", "price": "CAD $85.00"}
{"description": "SOFT AND SMOOTH", "name": "Jack Purcell Tumbled Leather Low Top", "price": "CAD $95.00"}
{"description": "VINTAGE DESIGN. BOLD STATEMENT.", "name": "Chuck 70 Wordmark Wool High Top", "price": "CAD $120.00"}
{"description": "REDEFINING THE PINSTRIPE", "name": "One Star Pinstripe Low Top", "price": "CAD $105.00"}
{"description": "SAY IT BOLDLY. \r\nIf you\u2019re going to make a statement, make it boldly. These Chuck Taylor All Star high top sneakers are all about that with a canvas upper, molded rubber tongue label and an oversized graphic logo. The OrthoLite insole for cushioning also helps to keep your feet happy as you show off your kicks. They\u2019re a style statement that speaks volumes from the moment you lace them up.", "name": "Chuck Taylor All Star Wordmark High Top", "price": "CAD $80.00"}
{"description": "SAY IT BOLDLY. \r\nIf you\u2019re going to make a statement, make it boldly. These Chuck Taylor All Star high top sneakers are all about that with a canvas upper, molded rubber tongue label and an oversized graphic logo. The OrthoLite insole for cushioning also helps to keep your feet happy as you show off your kicks. They\u2019re a style statement that speaks volumes from the moment you lace them up.", "name": "Chuck Taylor All Star Wordmark Low Top", "price": "CAD $75.00"}
{"description": "PREMIUM LEATHER LUXURY. Let\u2019s talk leather. These Chuck Taylor All Star low top sneakers were made for it. The leather upper features metal details for a smooth, easy to wear look. Lace them up high and wear them with confidence.", "name": "Chuck Taylor All Star Leather Low Top", "price": "CAD $85.00"}
{"description": "The Converse Chuck Taylor All Star Leather sneaker adds a rich, textured leather upper to the world's most iconic shoe. The vulcanized rubber sole, brushed metal eyelets, reinforced rubber toe cap, padded footbed and cultural authenticity remain intact.", "name": "Chuck Taylor All Star Leather Low Top", "price": "CAD $85.00"}
{"description": "TENNIS HERITAGE, HIJACKED FOR SKATE.", "name": "One Star CC Low Top", "price": "CAD $90.00"}
{"description": "STRAP IN FOR SERIOUS STYLE. The Converse Pro Blaze Strap is meant for the kid on the go. The premium leather upper helps keep these kicks looking fresh, no matter the adventure. Add in an ankle strap for a super secure fit, and you\u2019ve got yourselves a pair of kicks that are ready to take on the season.", "name": "Pro Blaze Strap High Top Infant/Toddler", "price": "CAD $60.00"}
{"description": "LIGHTWEIGHT CHAMBRAY, CLASSIC LOOK. Inspired by off court prep wear, the Chuck Taylor All Star 70s is all about daring details. The lightweight chambray upper features bold graphic details to set off your outfit. Plus, these kicks are built for comfort\u2014the durable vulcanized rubber sole and OrthoLite insole for cushioning make each step you take super comfy.  It\u2019s the perfect blend of sophisticated prep and street style.", "name": "Chuck 70 Prep Embroidery High Top", "price": "CAD $100.00"}
{"description": "Crafted from premium suede in a high-top profile, the Converse CONS CTAS Pro Suede\u00a0is ideal for the skater who wants maximum durability and support around the ankle. Nike Lunarlon cushioning helps cushion hard landings, while a CONS rubber outsole delivers superior grip and boardfeel.", "name": "CONS CTAS Pro Suede High Top", "price": "CAD $90.00"}
{"description": "BRING YOUR VARSITY SHOE GAME. Get into the game with the Chuck Taylor All Star Blocked Nubuck sneaker. These feminine color block kicks are inspired by classic varsity style with a premium nubuck upper. Inside you\u2019ll find an OrthoLite insole for cushioning to help keep you going, which is a major plus\u2014these kicks are perfect for transitioning from day to night.", "name": "Chuck Taylor All Star Blocked Nubuck Low Top", "price": "CAD $95.00"}
{"description": "BIG FASHION. BIG IMPRESSION. Amp up the drama with these Chuck Taylor All Star sneakers. With each pair you\u2019ll find the canvas upper you know and love, plus a few amped up details you didn't expect like large-scale eyelets and playful wide laces. Inside, you\u2019ll find an OrthoLite insole for cushioning. If you\u2019re looking for a bold twist on a classic kick, you\u2019ve got it right here.", "name": "Chuck Taylor All Star Big Eyelets Pastel Canvas Low Top", "price": "CAD $75.00"}
{"description": "BIG FASHION. BIG IMPRESSION. Amp up the drama with these Chuck Taylor All Star sneakers. With each pair you\u2019ll find the canvas upper you know and love, plus a few amped up details you didn't expect like large-scale eyelets and playful wide laces. Inside, you\u2019ll find an OrthoLite insole for cushioning. If you\u2019re looking for a bold twist on a classic kick, you\u2019ve got it right here.", "name": "Chuck Taylor All Star Big Eyelets Pastel Canvas High Top", "price": "CAD $80.00"}
{"description": "ICONIC PROFILE. NEW DIGS.", "name": "One Star Piping Low Top", "price": "CAD $105.00"}
{"description": "BRING YOUR VARSITY SHOE GAME. Get into the game with the Chuck Taylor All Star Blocked Nubuck sneaker. These feminine color block kicks are inspired by classic varsity style with a premium nubuck upper. Inside you\u2019ll find an OrthoLite insole for cushioning to help keep you going, which is a major plus\u2014these kicks are perfect for transitioning from day to night.", "name": "Chuck Taylor All Star Blocked Nubuck High Top", "price": "CAD $100.00"}
{"description": "STAND TALL. STAND OUT.", "name": "Chuck Taylor All Star Lift Ripple Canvas Low Top", "price": "CAD $85.00"}
{"description": "SNEAKERS WITH A SOFT SIDE. The Chuck Taylor All Star Peached sneakers are the perfect balance of softness and bite. The peached canvas upper is wildly soft to the touch and features transitional pastel colors, giving these kicks a nice feminine feel. But don\u2019t be fooled\u2014chrome hardware brings a special edge that\u2019s hard to ignore. With an OrthoLIte insole for cushioning, these kicks are perfect for expressing yourself all day long.", "name": "Chuck Taylor All Star Peached Wash Low Top", "price": "CAD $75.00"}
{"description": "A SOFTER SIDE OF THE STREETWEAR ICON.", "name": "One Star Peached Wash Low Top", "price": "CAD $90.00"}
{"description": "Jonathan Anderson is a British-based designer at the forefront of the international fashion scene. His collaborative collection with Converse, inspired by the friction of clashing ideas, brings high-end appeal to street-bound style. For his latest release with Converse, Anderson continues to explore the space between contrasting aesthetics and deconstructed textiles. Mashing up classic brogue shoe detailing, inverted suede, patchwork denim, and\u2014for the first time ever the Chuck 70 XX High silhouette\u2014the Simply_Complex pack examines the beauty between process and perfection.", "name": "Converse x JW Anderson Chuck 70 XX High Top", "price": "CAD $220.00"}
{"description": "ALMOST TOO EASY", "name": "Chuck Taylor All Star 2V Low Top Infant/Toddler", "price": "CAD $40.00"}
{"description": "STAND TALL AND SHINE.", "name": "Chuck Taylor All Star Lift Low Top", "price": "CAD $80.00"}
{"description": "FASHION MADE CONVENIENT", "name": "Chuck Taylor All Star 3V Low Top", "price": "CAD $85.00"}
{"description": "This is the iconic Converse Jack Purcell sneaker that has fundamentally gone unchanged since the 1930s. It has a durable canvas upper, canvas lining and removable EVA insert for comfort and medial-side air vent holes for breathability. Featuring traditional metal eyelets, a rubber-wrapped midsole, classic light-blue rubber outsole, and unmistakable toe cap smile, it\u2019s easy to see why the Jack Purcell look has stood the test of time.", "name": "Jack Purcell Canvas Classic Low Top", "price": "CAD $75.00"}
{"description": "CLASSIC LOOK, SLIMMED DOWN. Bring on the spring with the Chuck Taylor All Star Dainty sneaker. These kicks are blooming with brand new colours for the season, complete with a canvas upper, woven tongue label and an EVA insole for cushioning. They\u2019re the type of kicks that look and feel fresh, and that\u2019s what spring is all about.", "name": "Chuck Taylor All Star Dainty Low Top", "price": "CAD $65.00"}
{"description": "MONO GLAM REALNESS. Say hello to the beautiful simplicity of the Chuck Taylor All Star Mono Glam sneaker. These low top kicks feature a canvas upper, a medial patch and a buttery smooth monochromatic design. Wear them as a sleek addition to your favorite outfit.", "name": "Chuck Taylor All Star Mono Glam Low Top", "price": "CAD $65.00"}
{"description": "MONO GLAM REALNESS. Say hello to the beautiful simplicity of the Chuck Taylor All Star Mono Glam sneaker. These high top kicks feature a canvas upper, a medial patch and a buttery smooth monochromatic design. Wear them as a sleek addition to your favorite outfit.", "name": "Chuck Taylor All Star Mono Glam High Top", "price": "CAD $70.00"}
{"description": "A CLASSIC KIND OF SMOOTH. This season, you\u2019ve got a whole new reason to love the Chuck Taylor All Star low top. These kicks bring the magic of a faux leather upper for a chic look and a lace-up closure for security. Style them any day you\u2019d like\u2014they\u2019re made to bring out the best of your personal style.", "name": "Chuck Taylor All Star Craft SL Low Top", "price": "CAD $75.00"}
{"description": "NOTHIN\u2019 WRONG WITH NEUTRAL. Shift into neutral gear with these Chuck Taylor All Star sneakers. Featuring muted neutrals and smooth tones, these classic kicks are great for adding a sleek touch to your wardrobe. When you lace them up you know it\u2019s about to be a good one.", "name": "Chuck Taylor All Star Craft SL High Top", "price": "CAD $80.00"}
{"description": "FADE INTO FASHION. Your favorite Chuck Taylor All Star sneakers are getting all dressed up. It starts with the ombre metallic canvas upper which creates a cool gradient look from front to back. These kicks feature other fine details like aluminum eyelets, a woven tongue label and an OrthoLite insole for cushioning. Lace them up and feel the fade.", "name": "Chuck Taylor All Star Ombre Metallic Low Top", "price": "CAD $75.00"}
{"description": "HOOK AND LOOP FOR THE WIN. Go for the easy win with the Chuck Taylor All Star 3V sneakers. The canvas upper is tried and true, meant for great-looking durability. With three hook and loop closure for easy on and off, they\u2019re the kind of kicks that kids and parents love alike.", "name": "Chuck Taylor All Star 3V Canvas Low Top", "price": "CAD $75.00"}
{"description": "ATTITUDE BY THE BOW. Your attitude is front and center with the Chuck Taylor All Star Knot. The canvas upper features an oversized bow that you can tie any way you want\u2014big, small, dramatic or perfectly tailored. Inside, the personality stays strong with a star print lining and an EVA insole for cushioning. Lace them up and step strong.", "name": "Chuck Taylor All Star Knot Low Top", "price": "CAD $65.00"}
{"description": "GET STACKED", "name": "One Star Platform Low Top", "price": "CAD $120.00"}
{"description": "The Converse Chuck Taylor First Star\u00a0Bootie\u00a0reimagines\u00a0the iconic original\u00a0for the littlest movers and shakers with a flexible leather upper.", "name": "Chuck Taylor First Star Leather Infant/Toddler", "price": "CAD $40.00"}
{"description": "The Converse Chuck Taylor First Star Bootie recalls the iconic original for the littlest movers and shakers with a flexible canvas upper and comfortable lace-up design.", "name": "Chuck Taylor First Star Canvas Infant/Toddler", "price": "CAD $35.00"}
{"description": "CLASSIC AND COOL. When you\u2019re going for a classic look, check out the Chuck Taylor All Star Street sneakers. These kicks start with a durable canvas upper and a comfortable lace-up closure. They\u2019re a clean addition to any little outfit.", "name": "Chuck Taylor All Star Street Mid Infant/Toddler", "price": "CAD $45.00"}
{"description": "GLITTER FOR FUN. Let your little one\u2019s personality shine with the Chuck Taylor All Star 2V Glitter sneaker. The glitter upper is perfectly fun when it comes to little feet, and the double hook and loop closure makes things a whole lot easier. Just strap up and show those off.", "name": "Chuck Taylor All Star 2V Glitter Low Top Infant/Toddler", "price": "CAD $45.00"}
{"description": "BOLD AND COMFY KICKS. Show your outfit some love with the Chuck Taylor All Star low top sneaker. These canvas kicks feature a comfortable and durable canvas upper, perfect for showing off your personality. Plus, the OrthoLite insole for cushioning is sure to keep your comfy, so you can keep it kickin\u2019 all day long.", "name": "Chuck Taylor All Star Bleeding Love Low Top", "price": "CAD $75.00"}
{"description": "EASY ON. EASY OFF. There\u2019s the battle to get the sneakers on and the battle to get them off. Then there\u2019s the Chuck Taylor All Star 2V. These sneakers are inspired by the iconic Converse look, and include a canvas upper and a hook and loop closure, perfect for making quick work out of sneaker time.", "name": "Chuck Taylor All Star 2V Seasonal Low Top Infant/Toddler", "price": "CAD $40.00"}
{"description": "Time-honored classics merged with future fibres. By stretching a sneaker icon to new heights with the XX High, JW Anderson reenvisioned an entirely new Chuck 70 that\u2019s been over a century in the making.", "name": "Converse x JW Anderson Chuck 70 XX High Top", "price": "CAD $180.00"}
{"description": "FASHION FOR LITTLE FEET. Keep things chic and simple in these Chuck Taylor All Star Simple Step sneakers. Made to keep little feet comfortable, these canvas kicks feature an adjustable lace-up closure, medial All Star logo and fun colors to keep things interesting.", "name": "Chuck Taylor All Star Simple Step High Top Infant/Toddler", "price": "CAD $45.00"}
{"description": "Time-honored classics merged with future fibres. Infusing ballet-slipper inspiration and his unique creative approach into an enduring basketball icon, JW Anderson has evolved a classic into an entirely new silhouette.", "name": "Converse x JW Anderson Chuck 70 U-Throat Ballet Low Top", "price": "CAD $140.00"}
{"description": "NEXT LEVEL HERRINGBONE STYLE.\r\nGo for sky-high breathable style with the Chuck Taylor All Star Lift sneaker. The mesh upper features a playful herringbone pattern for the perfect summertime look. With luxe leather details and a chic stacked rubber sole, these are the kind of shoes you\u2019re going to want to show off. With a comfortable EVA insole for cushioning, you can wear these to any of your favorite summer activities from music festivals to family cookouts.", "name": "Chuck Taylor All Star Lift Herringbone Mesh Low Top", "price": "CAD $80.00"}
{"description": "VINTAGE FEEL. MODERN DETAILS. Comfort and the tropics collide in this beautifully crafted Chuck Taylor All Star 70 sneaker. Our vintage heritage canvas upper features a palm print graphic and floral embroidery for a fresh, bold look. But the details don\u2019t stop there\u2014the varnished midsole, embossed medial patch and OrthoLite insole for cushioning make these kicks hard to resist.", "name": "Chuck 70 Palm Print Low Top", "price": "CAD $90.00"}
{"description": "VINTAGE FEEL. MODERN DETAILS. Comfort and the tropics collide in this beautifully crafted Chuck Taylor All Star 70 sneaker. Our vintage heritage canvas upper features a palm print graphic and floral embroidery for a fresh, bold look. But the details don\u2019t stop there\u2014the varnished midsole, embossed medial patch and OrthoLite insole for cushioning make these kicks hard to resist.", "name": "Chuck 70 Palm Print High Top", "price": "CAD $110.00"}
{"description": "ELEVATED FASHION. This summer is all about living carefree in the Chuck Taylor All Star Lift. The canvas upper features fresh new colours, perfect for celebrating the season and your bold style. The stack sole elevates any look while the EVA insole for cushioning adds even more comfort. Stomp around to your heart\u2019s content\u2014no one\u2019s stopping you in these super fly kicks.", "name": "Chuck Taylor All Star Lift Canvas Low Top", "price": "CAD $75.00"}
{"description": "FOR SOME, ONE TONE ISN'T ENOUGH.", "name": "Chuck Taylor All Star Hyper Light Low Top Little/Big Kids", "price": "CAD $60.00"}
{"description": "HOOK AND LOOP FOR THE WIN. Go for the easy win with the Chuck Taylor All Star 3V sneakers. The canvas upper is tried and true, meant for great-looking durability. With three hook and loop closure for easy on and off, they\u2019re the kind of kicks that kids and parents love alike.", "name": "Chuck Taylor All Star 3V Low Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "FUN COLOR MIDSOLES. Give your little star  a classic look with the Chuck Taylor All Star Street sneakers. These kicks start with a durable canvas upper and a comfortable slip-on closure, and feature details like color midsoles for a fun touch. They\u2019re a clean addition to any outfit.", "name": "Chuck Taylor All Star Street Mid Tri-Block Infant/Toddler", "price": "CAD $45.00"}
{"description": "ALL-WEATHER STYLE AND PROTECTION.  The Chuck Taylor All Star Waterproof Boot Leather is prepared to keep you warm, dry and comfortable this winter season, no matter what Mother Nature is throwing at you. Part of our Converse Counter Climate collection, the sleek, weatherproof leather and inner neoprene bootie construction will fight back the cold and wet. The Nike Lunarlon sockliner delivers all-day cushioning and comfort, while the lugged, 100% rubber outsole provides traction.", "name": "Chuck Taylor All Star Waterproof Boot Leather High Top", "price": "CAD $150.00"}
{"description": "The Converse Chuck Taylor All Star Shoreline\u00a0lets you slip on your Chucks and head out, with an elasticized collar and no-tie design.", "name": "Chuck Taylor All Star Shoreline", "price": "CAD $60.00"}
{"description": "CLASSIC AND COOL. When you\u2019re going for a classic look, check out the Chuck Taylor All Star Street sneakers. These kicks start with a durable canvas upper and a comfortable lace-up closure, and feature details like color midsoles for a fun touch. They\u2019re a clean addition to any outfit.", "name": "Chuck Taylor All Star Street Mid Tri-Block Little/Big Kids", "price": "CAD $50.00"}
{"description": "SLIP ON FUN. Sometimes, it\u2019s best to stick with a classic. The Chuck Taylor All Star Street is all about what you bring to it\u2014your personality, your style. The canvas upper is comfortable and durable, complete with an accent color tongue. Just slip them on and let your style speak for itself.", "name": "Chuck Taylor All Star Street Slip Little/Big Kids", "price": "CAD $50.00"}
{"description": "FUN STREET STYLE. Bring some street style to your wardrobe with the Chuck Taylor All Star High Street sneakers. Oxford profile is built for comfort with a durable canvas upper and a lace-up closure. Plus, they\u2019re made to last so you can hit the ground running.", "name": "Chuck Taylor All Star High Street High Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "TWO-TONE STREET STYLE. Bring some street style to your little one\u2019s wardrobe with the Chuck Taylor All Star High Street sneakers. The two-tone upper is built for comfort with durable canvas and a slip-on closure. Plus, they\u2019ve got an EVA insole for cushioning and comfort so your little one can get to kicking.", "name": "Chuck Taylor All Star Street Fundamentals Low Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "STAND TALL", "name": "Chuck Taylor All Star Lift Low Top", "price": "CAD $75.00"}
{"description": "ZIP UP. GAME ON. Zip into the season with the Chuck Taylor All Star Sport Zip. These sneakers feature a canvas upper with cool zip detail to add a little edge to your look. The cool thing is that these kicks also feature a lace-up closure for total foot security without sacrificing fashion. That\u2019s a major win.", "name": "Chuck Taylor All Star Sport Zip High Top Little/Big Kids", "price": "CAD $55.00"}
{"description": "EASY ON. EASY OFF. There\u2019s the battle to get the sneakers on and the battle to get them off. Then there\u2019s the Chuck Taylor All Star 2V. These sneakers are inspired by the iconic Converse look, and include a canvas upper and a hook and loop closure, perfect for making quick work out of sneaker time.", "name": "Chuck Taylor All Star 2V Fundamentals Low Top Infant/Toddler", "price": "CAD $40.00"}
{"description": "A PLAYFUL TAKE ON A FAVORITE. Go for breathable style with the Chuck Taylor All Star low top sneaker. The mesh upper features a playful herringbone pattern for the perfect summertime look. With luxe leather details on the logo and heel stay these are the kind of shoes you\u2019re going to want to show off. Inside, you\u2019ll find an OrthoLite insole for cushioning. Wear these to any of your favorite summer activities from music festivals to family cookouts.", "name": "Chuck Taylor All Star Herringbone Mesh Low Top", "price": "CAD $70.00"}
{"description": "STRAP IN FOR SERIOUS STYLE. The Converse Pro Blaze Strap is meant for the kid on the go. The premium leather upper helps keep these kicks looking fresh, no matter the adventure. Add in an ankle strap for a super secure fit, and you\u2019ve got yourselves a pair of kicks that are ready to take on the season.", "name": "Pro Blaze Strap High Top Little/Big Kids", "price": "CAD $65.00"}
{"description": "The Converse Chuck Taylor All Star Dainty\u00a0lends a slender look to the iconic sneaker with thinner foxing tape and a super-low profile.", "name": "Chuck Taylor All Star Dainty Low Top", "price": "CAD $65.00"}
{"description": "COMFORTABLE FIT. DOUBLY CHIC. Step out in double the style with the Chuck Taylor All Star Double Tongue. It starts with the iconic Chuck Taylor silhouette and a durable canvas upper. The extra flair comes in a fun double tongue, perfect for adding a fun touch to any outfit.", "name": "Chuck Taylor All Star Double Tongue Low Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "FOR GLITTERING STEPS. You can never have too much glitter. That\u2019s why the Chuck Taylor All Star Glitter sneakers are perfect for adding a cool element to your wardrobe. They\u2019re colorful, eye-catching and so easy to smile about.", "name": "Chuck Taylor All Star Glitter Low Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "BABY'S NEW FAVORITE KICKS. Bring on bold colors with the Chuck Taylor All Star Madison. These well-loved kicks feature a durable canvas upper, now in new colors to take on the new season. They're perfect for pairing with any adorable outfit your little one dons.", "name": "Chuck Taylor All Star Madison Low Top Infant/Toddler", "price": "CAD $45.00"}
{"description": "HOOK AND LOOP. BEACH INSPIRED. Your little one can enjoy fun in the sun with the Chuck Taylor All Star 2V sneakers. The palm tree graphic is inspired by sunny times at the beach, the ultimate summer activity. These kicks feature two hook and loop closures for easy on and off, so you can get to family beach time faster than ever.", "name": "Chuck Taylor All Star 2V Palm Trees Low Top Infant/Toddler", "price": "CAD $45.00"}
{"description": "YOUR NEW FAVORITE KICKS. Bring on bold colors with the Chuck Taylor All Star Madison. These well-loved kicks feature a durable canvas upper, now in new colors to take on the new season. Lace them up and wear them out on your next adventure.", "name": "Chuck Taylor All Star Madison Low Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "CLASSIC AND COOL. When you\u2019re going for a classic look, check out the Chuck Taylor All Star Street. With a durable canvas upper and a comfortable lace-up closure, they\u2019re a super clean addition to any outfit.", "name": "Chuck Taylor All Star Street Fundamentals Mid Little/Big Kids", "price": "CAD $50.00"}
{"description": "BUILT FOR ADVENTURE. The Chuck Taylor All Star High Street is a comfortable classic that\u2019s built to keep up with your little one. With a durable canvas upper, comfortable slip-on closure, and an EVA insole for cushioning, these kicks are built for comfort and style.", "name": "Chuck Taylor All Star High Street Heather Textile High Top Infant/Toddler", "price": "CAD $45.00"}
{"description": "TWO TIMES THE SUN. Your days will be doubly sunny in the Chuck Taylor All Star Double Tongue. The canvas upper features a playful palm tree graphic, perfect for celebrating the season in style. The double tongue adds another level of fun and fashion, so you can be sure you\u2019re making a statement everywhere you go.", "name": "Chuck Taylor All Star Double Tongue Palm Trees Low Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "BUILT FOR ADVENTURE. The Chuck Taylor All Star High Street is a comfortable classic that\u2019s built to keep up with you. With a durable canvas upper, a secure high top build, and an EVA insole for cushioning, these lace-up kicks are built for comfort and style. When you lace them up, you know you\u2019re going to have a big day with a few surprise adventures. And surely you wouldn\u2019t have it any other way.", "name": "Chuck Taylor All Star High Street Heather Textile High Top Little/Big Kids", "price": "CAD $55.00"}
{"description": "STYLE AND SECURITY IN ONE. Comfort is king in the Pro Blaze Strap sneaker. The durable canvas upper features a prominent Star Chevron logo, a nod to Converse\u2019s unique history. The ankle strap closure and bold colours give these kicks a little extra edge while also offering a secure fit for little feet.", "name": "Pro Blaze Strap Canvas High Top Infant/Toddler", "price": "CAD $55.00"}
{"description": "YOUR NEW FAVORITE KICKS. Bring on bold colors with the Chuck Taylor All Star Madison. These well-loved kicks feature a durable canvas upper, now in new colors to take on the new season. Lace them up and wear them out on your next adventure.", "name": "Chuck Taylor All Star Madison Palm Trees Low Top Little/Big Kids", "price": "CAD $55.00"}
{"description": "The Converse CONS CTAS Pro Suede delivers the durability and impact protection needed for any style of skateboarding with a suede upper and plush Nike Lunarlon cushioning. The low profile offers total flexibility, while the rubber outsole enhances boardfeel and grip.", "name": "CONS CTAS Pro Suede Low Top", "price": "CAD $85.00"}
{"description": "The Converse CONS CTAS Pro is ideal for the skater who wants a minimal, low-profile construction for superior boardfeel and flexibility. Designed to stand up to wear and tear, the CONS CTA Pro features rubber-infused canvas and a skate-specific outsole, while Nike Lunarlon cushioning helps absorb impact during jumps and tricks.", "name": "CONS CTAS Pro Low Top", "price": "CAD $80.00"}
{"description": "WEATHERPROOF PROTECTION. The Chuck Taylor All Star Waterproof Boot Quilted Leather is designed and equipped to battle the harshest of seasonal elements, while upholding the classic Chuck Taylor All-Star profile. Inside the stylish but tough quilted leather construction is a waterproof neoprene booty with Thinsulate insulation that renders slush puddles powerless. A Nike Lunarlon sockliner delivers premium cushioning and the lugged, 100% rubber outsole keeps you moving with superior traction. Jack Frost just threw in the towel.", "name": "Chuck Taylor All Star Waterproof Boot Quilted Leather", "price": "CAD $150.00"}
{"description": "The Converse Chuck Taylor All Star Mono Leather sneaker adds a rich, textured leather upper onto the world\u2019s most iconic high top. The classic star-centered ankle patch, vulcanized rubber sole, brushed metal eyelets, reinforced rubber toe cap, padded footbed and cultural authenticity remain intact.", "name": "Chuck Taylor All Star Mono Leather High Top", "price": "CAD $90.00"}
{"description": "BRACED FOR ADVENTURE. The Chuck Taylor All Star Pro is going heavy duty. The rubber-backed suede upper and Cons traction rubber are perfect for increased durability. These kicks are also built to keep you comfy and protected. Inside you\u2019ll find an OrthoLite insole and a Nike Zoom Air technology in the heel for cushioning. So if you\u2019re planning a hardcore adventure, let these be your sidekicks.", "name": "CTAS Pro High Top", "price": "CAD $90.00"}
{"description": "NUBUCK IS A TYPE OF LEATHER. Pretty much waterproof.", "name": "Chuck Taylor All Star Waterproof Nubuck Boot", "price": "CAD $150.00"}
{"description": "THE ICON, BUILT TO SKATE.", "name": "CTAS Pro Low Top", "price": "CAD $85.00"}
{"description": "KICKS THAT GET BETTER WITH TIME. Don\u2019t let the name fool you. The Chuck Taylor All Star Stone Wash sneakers are all about being soft to the touch. The wash process gives the canvas upper a worn-in appearance and a soft feel that only gets better with time. In addition, the OrthoLite insole for cushioning help keeps your steps soft, too. They\u2019re the coziest in the sneaker game.", "name": "Chuck Taylor All Star Stone Wash Low Top", "price": "CAD $75.00"}
{"description": "KICKS THAT GET BETTER WITH TIME. Don\u2019t let the name fool you. The Chuck Taylor All Star Stone Wash sneakers are all about being soft to the touch. The wash process gives the canvas upper a worn-in appearance and a soft feel that only gets better with time. In addition, the OrthoLite insole for cushioning help keeps your steps soft, too. They\u2019re the coziest in the sneaker game.", "name": "Chuck Taylor All Star Stone Wash High Top", "price": "CAD $80.00"}
{"description": "REDEFINING THE PINSTRIPE", "name": "One Star Pinstripe Low Top", "price": "CAD $100.00"}
{"description": "OUTFITTED FOR THE URBAN BATTLEGROUND", "name": "One Star Camo Low Top", "price": "CAD $100.00"}
{"description": "OUTFITTED FOR THE URBAN BATTLEGROUND", "name": "One Star Camo Mid", "price": "CAD $110.00"}
{"description": "CHUCK, LUXE.", "name": "Chuck Taylor All Star Nubuck High Top", "price": "CAD $90.00"}
{"description": "BRING ON THE BEACH. When the sun comes out, that means it\u2019s time for a good beach day. These Chuck Taylor All Star high top sneakers are bringing the summertime vibes with a durable canvas upper and palm tree graphic, inspired by the beach. Rock them with your favorite shorts and get ready for a little seasonal fun.", "name": "Chuck Taylor All Star Palm Trees High Top Little/Big Kids", "price": "CAD $50.00"}
{"description": "VINTAGE DESIGN. FRESH LOOK.", "name": "Chuck 70 Vintage Canvas High Top", "price": "CAD $90.00"}
{"description": "VINTAGE DESIGN. FRESH LOOK.", "name": "Chuck 70 Vintage Canvas Low Top", "price": "CAD $85.00"}
{"description": "LIGHTWEIGHT CHAMBRAY, CLASSIC LOOK. Inspired by off court prep wear, the Chuck Taylor All Star 70s is all about daring details. The lightweight chambray upper features bold graphic details to set off your outfit. Plus, these kicks are built for comfort\u2014the durable vulcanized rubber sole and OrthoLite insole for cushioning make each step you take super comfy.  It\u2019s the perfect blend of sophisticated prep and street style.", "name": "Chuck 70 Prep Embroidery Low Top", "price": "CAD $90.00"}
{"description": "VINTAGE STYLE. MODERN COMFORT. Our Chuck Taylor All Star 70 high top sneaker is a classic look that will never let you down. The vintage canvas upper is as easy to wear as it is chic, complete with tonal pinstripes. The bottom of the shoe also features a tri-colour pinstripe for added detail, inspired by classic colour blocking trends. Inside, the OrthoLite insole for cushioning brings a modern sense of comfort to these iconic kicks.", "name": "Chuck 70 Heritage Court High Top", "price": "CAD $90.00"}
{"description": "VINTAGE STYLE. MODERN COMFORT. Our Chuck Taylor All Star 70 low top sneaker is a classic look that will never let you down. The vintage canvas upper is as easy to wear as it is chic, complete with tonal pinstripes. The bottom of the shoe also features a tri-colour pinstripe for added detail, inspired by classic colour blocking trends. Inside, the OrthoLite insole for cushioning brings a modern sense of comfort to these iconic kicks.", "name": "Chuck 70 Heritage Court Low Top", "price": "CAD $85.00"}
{"description": "THE ICON, REBUILT TO SKATE. The Converse CONS CTAS Pro Purple High Top Men's Skateboarding Shoe is a premium offering celebrating Converse Skateboarding\u2019s first full-length skate film, PURPLE (May 2018).", "name": "CONS Purple CTAS Pro High Top", "price": "CAD $90.00"}
{"description": "THE COLOURS OF THE SEASON. When you lace up the Chuck Taylor All Star high top sneakers, you\u2019re agreeing to start your season with a bang. These canvas sneakers feature the iconic style you know and love with bold new color updates to bring added flair to your spring wardrobe. Style them up and step out.", "name": "Chuck Taylor All Star Seasonal High Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "Modified by Hockey pro and Bloby member in good standing, The CTAS Pro x Kevin Rodrigues is the Chuck Taylor two-pack everyone\u2019s hoped for - High-top or low, it\u2019s your choice. A perfect weapon for the wallride, poll-jam, slappy war we\u2019re currently enjoying.", "name": "CTAS Pro x Kevin Rodrigues Low Top", "price": "CAD $95.00"}
{"description": "Edgy, bold and glittery all over.", "name": "Converse x Miley Cyrus Chuck Taylor All Star High Top", "price": "CAD $90.00"}
{"description": "STYLE AND SECURITY IN ONE. Comfort is king in the Pro Blaze Strap sneaker. The durable canvas upper features a prominent Star Chevron logo, a nod to Converse\u2019s unique history. The ankle strap closure gives these kicks a little extra edge while also offering a secure fit for small feet. Enjoy these sneakers in bold colours to complement your personal style.", "name": "Pro Blaze Strap Canvas High Top Little/Big Kids", "price": "CAD $60.00"}
{"description": "CHUCK, LUXE.", "name": "Chuck Taylor All Star Nubuck Low Top", "price": "CAD $85.00"}
{"description": "A little bit country, a little bit punk rock.", "name": "Converse x Miley Cyrus Chuck Taylor All Star High Top", "price": "CAD $90.00"}
{"description": "ALL EYES ON THE ONE STAR. The One Star, reimagined by Chiara Ferragni, with her iconic embroidered eye logo, and all-over glitter finish.", "name": "Converse x Chiara Ferragni One Star Platform Low Top", "price": "CAD $170.00"}
{"description": "STAND OUT \u2013 BLEND IN. A refreshing new twist on street-style classics.", "name": "Converse X Sneakersnstuff One Star Low Top", "price": "CAD $140.00"}
{"description": "FEMALE TROUBLE FOREVER. Inspired by the spirit of Downtown NYC, the energy of the Riot Grrrl movement, and early 90s subcultures, MadeMe is a brand that champions a by-girls for-girls style that deviates from the male-dominated sportswear market. Converse and MadeMe have now teamed up for a capsule collection that merges MadeMe's inimitable cool-girl style with the iconic One Star of Converse.  This rave-inspired, elevated platform take on the One Star Low serves as the centerpiece for this limited-edition range, with springtime staples like tracksuits and baby backpacks rounding out the collection.", "name": "Converse x MadeMe One Star Platform Low Top", "price": "CAD $150.00"}
{"description": "FEMALE TROUBLE FOREVER. Inspired by the spirit of Downtown NYC, the energy of the Riot Grrrl movement, and early 90s subcultures, MadeMe is a brand that champions a by-girls for-girls style that deviates from the male-dominated sportswear market. Converse and MadeMe have now teamed up for a capsule collection that merges MadeMe's inimitable cool-girl style with the iconic One Star of Converse.  This rave-inspired, elevated platform take on the One Star Low serves as the centerpiece for this limited-edition range, with springtime staples like tracksuits and baby backpacks rounding out the collection.", "name": "Converse x MadeMe One Star Platform Low Top", "price": "CAD $150.00"}
{"description": "Converse Pride x Miley Cyrus Chuck Taylor All Star Platform High Top", "name": "Converse Pride x Miley Cyrus Chuck Taylor All Star Platform High Top", "price": "CAD $120.00"}
{"description": "Converse Pride x Miley Cyrus Chuck Taylor All Star High Top", "name": "Converse Pride x Miley Cyrus Chuck Taylor All Star High Top", "price": "CAD $90.00"}
{"description": "Converse Pride x Miley Cyrus Chuck Taylor All Star Low Top", "name": "Converse Pride x Miley Cyrus Chuck Taylor All Star Low Top", "price": "CAD $85.00"}
{"description": "CRISP POLKA DOT STYLE. We\u2019re doing dots in a brand new way with the Chuck Taylor All Star sneaker. These crisp, clean polka dots in totally unexpected ways\u2014across the durable canvas upper and sprinkled over the midsole. The OrthoLite insole for cushioning helps to keep you comfortable so you can rock your edgy look all day long. Go for dots that break outside the box and keep things funky, no matter what you pair them with.", "name": "Chuck Taylor All Star Polka Dots High Top", "price": "CAD $75.00"}
{"description": "Converse Pride x Miley Cyrus Chuck 70 High Top", "name": "Converse Pride x Miley Cyrus Chuck 70 High Top", "price": "CAD $140.00"}
{"description": "THE FEELING OF SUMMER. Inspired by the heat of summer, these washed linen sneakers bring that light, airy feeling. The laid back vibe is complemented by sleek details like gold eyelets, frayed tip lace and an EVA insole for cushioning. Lace them up and feel the summer breeze float by.", "name": "Chuck Taylor All Star Washed Linen Low Top", "price": "CAD $75.00"}
{"description": "EXPRESS YOUR EDGY SIDE. Bring a little edge to your outfit with the Converse Embroidered Mesh Boxy Tee. It\u2019s all about expressing yourself and staying comfortable with a poly spandex mesh construction, split hem and comfy dropped shoulder. Add your own accessories to dress it up your way and let your personality shine.", "name": "Women's Embroidered Mesh Boxy T-Shirt", "price": "CAD $50.00"}
{"description": "LIGHTWEIGHT SUMMER CROP. Slip into a comfy crop with the Core Essentials Lightweight Cropped Palm Print hoodie. It\u2019s made with an ultra soft, lightweight French terry for supreme comfort. This soft crop also features front pockets for storage, and an adjustable waistband drawcord so you can make sure it fits your style just right. It\u2019s a fun street look with endless style options.", "name": "Women's Essentials Lightweight Cropped Palm Print Pullover Hoodie", "price": "CAD $110.00"}
{"description": "A little bit country, a little bit punk rock.", "name": "Converse x Miley Cyrus Bandana Bra Top", "price": "CAD $55.00"}
{"description": "A little bit country, a little bit punk rock.", "name": "Converse x Miley Cyrus Bandana Bra Top", "price": "CAD $55.00"}
{"description": "A little bit country, a little bit punk rock.", "name": "Converse x Miley Cyrus Bandana Track Pullover Hoodie", "price": "CAD $90.00"}
{"description": "Edgy, bold and glittery all over.", "name": "Converse x Miley Cyrus Glitter Track Jacket", "price": "CAD $120.00"}
{"description": "FEMALE TROUBLE FOREVER. Inspired by the spirit of Downtown NYC, the energy of the Riot Grrrl movement, and early 90s subcultures, MadeMe is a brand that champions a by-girls for-girls style that deviates from the male-dominated sportswear market. Converse and MadeMe have now teamed up for a capsule collection that merges MadeMe's inimitable cool-girl style with the iconic One Star of Converse.  This rave-inspired, elevated platform take on the One Star Low serves as the centerpiece for this limited-edition range, with springtime staples like tracksuits and baby backpacks rounding out the collection.", "name": "Converse x MadeMe Hooded Track Jacket", "price": "CAD $120.00"}
{"description": "FEMALE TROUBLE FOREVER. Inspired by the spirit of Downtown NYC, the energy of the Riot Grrrl movement, and early 90s subcultures, MadeMe is a brand that champions a by-girls for-girls style that deviates from the male-dominated sportswear market. Converse and MadeMe have now teamed up for a capsule collection that merges MadeMe's inimitable cool-girl style with the iconic One Star of Converse.  This rave-inspired, elevated platform take on the One Star Low serves as the centerpiece for this limited-edition range, with springtime staples like tracksuits and baby backpacks rounding out the collection.", "name": "Converse x MadeMe Track Pant", "price": "CAD $110.00"}
{"description": "FEMALE TROUBLE FOREVER. Inspired by the spirit of Downtown NYC, the energy of the Riot Grrrl movement, and early 90s subcultures, MadeMe is a brand that champions a by-girls for-girls style that deviates from the male-dominated sportswear market. Converse and MadeMe have now teamed up for a capsule collection that merges MadeMe's inimitable cool-girl style with the iconic One Star of Converse.  This rave-inspired, elevated platform take on the One Star Low serves as the centerpiece for this limited-edition range, with springtime staples like tracksuits and baby backpacks rounding out the collection.", "name": "Converse x MadeMe Long Sleeve T-Shirt", "price": "CAD $75.00"}
{"description": "Converse Pride x Miley Cyrus Polka Dot T-Shirt", "name": "Converse Pride x Miley Cyrus Polka Dot T-Shirt", "price": "CAD $50.00"}
{"description": "ALL EYES ON THE ONE STAR. The One Star, reimagined by Chiara Ferragni, with her iconic embroidered eye logo, and all-over glitter finish.", "name": "Converse x Chiara Ferragni One Star Low Top", "price": "CAD $160.00"}
{"description": "Converse Pride x Miley Cyrus Track Pant", "name": "Converse Pride x Miley Cyrus Track Pant", "price": "CAD $100.00"}
{"description": "NUBUCK COLOR BLOCKING. We\u2019re going full on color block with the Chuck Taylor All Star high top sneaker. The premium nubuck upper lends a clean look to these kicks while the color blocked design gives it just the right amount of edge. Lace them up your way and head out the door.", "name": "Chuck Taylor All Star Blocked Nubuck High Top", "price": "CAD $100.00"}
{"description": "The Chuck Taylor All Star 70 sneaker is bringing a brand new look to this vintage style. The durable canvas upper is elevated with a unique wash and painted midsole to give these kicks a faded appearance, inspired by the naturally sunbaked street courts of summer. Featuring the always-comfortable OrthoLite insole for cushioning, this look is totally new, totally unique, and ready to be styled.", "name": "Chuck 70 Overdyed Wash High Top", "price": "CAD $95.00"}
{"description": "STEP INTO LAVISH LEATHER. When it comes to tennis season, the colour white is a crisp, clean mainstay. In the One Star sneaker, we created new ways to style this signature colour while still keeping each design unique.  This pair is crafted with a tumbled leather upper for an elevated look. With an EVA insole for cushioning, they\u2019re so chic and comfy that you\u2019ll want to get right out there on the court.", "name": "One Star Grand Slam Low Top", "price": "CAD $105.00"}
{"description": "TIME TO GET PATRIOTIC. Celebrate the red, white and blue with our bold Chuck Taylor All Star sneakers. These kicks feature a perforated star and dot canvas upper, silver eyelets and an OrthoLite insole for cushioning.  They\u2019re the perfect way to show off your patriotic side, so lace them up and wear them boldly all summer long.", "name": "Chuck Taylor All Star Perforated Star Low Top", "price": "CAD $70.00"}
{"description": "STYLE TO REFLECT ON. When it comes to tennis season, the colour white is a crisp, clean mainstay. In the One Star sneaker, we created new ways to style this signature colour while still keeping each design unique.  This pair is crafted with a reflective leather upper for a fun take on a classic sneaker. With an EVA insole for cushioning, they\u2019re so chic and comfy that you\u2019ll want to get right out there on the court.", "name": "One Star Grand Slam Low Top", "price": "CAD $105.00"}
{"description": "SWING INTO SUEDE. When it comes to tennis season, the colour white is a crisp, clean mainstay. In the One Star sneaker, we created new ways to style this signature colour while still keeping each design unique.  This pair is crafted with a hairy suede upper for a fun textural element. With an EVA insole for cushioning, they\u2019re so chic and comfy that you\u2019ll want to get right out there on the court.", "name": "One Star Grand Slam Low Top", "price": "CAD $105.00"}
{"description": "MAKE SOME RACKET. When it comes to tennis season, the colour white is a crisp, clean mainstay. In the One Star sneaker, we created new ways to style this signature colour while still keeping each design unique.  This pair is crafted with a perforated leather upper for a chic, carefully crafted look. With an EVA insole for cushioning, they\u2019re so chic and comfy that you\u2019ll want to get right out there on the court.", "name": "One Star Grand Slam Low Top", "price": "CAD $105.00"}
{"description": "BUILT FOR SKATEBOARDING. The classic One Star sneaker, re-engineered for skateboarding with a durable suede upper, CONS Traction Rubber for grip, and an OrthoLite\u00ae insole with Nike Zoom Air technology for cushioning.", "name": "One Star Pro Suede Low Top", "price": "CAD $90.00"}
{"description": "All new, never-seen-before GOLF le FLEUR* Collection brought to you by Tyler, The Creator and Converse.", "name": "GOLF le FLEUR* One Star Suede Low Top", "price": "CAD $140.00"}
{"description": "TRANQUIL, BOTANIC-INSPIRED NEUTRALS. Inspired by luscious botanical gardens, these Chuck Taylor All Star low top sneakers are a modern take on neutrals. The canvas upper features a tonal treatment that extends to the midsole, which really accentuates the succulent garden tones. With a classic rubber outsole and OrthoLite\u00ae insole for cushioning, they feel as tranquil as they look. Try these sneakers for a peaceful take on the neutral trend.", "name": "Chuck Taylor All Star Botanical Neutrals Low Top", "price": "CAD $65.00"}
{"description": "TRANQUIL, BOTANIC-INSPIRED NEUTRALS. Inspired by luscious botanical gardens, these Chuck Taylor All Star high top sneakers are a modern take on neutrals. The canvas upper features a tonal treatment that extends to the midsole, which really accentuates the succulent garden tones. With a classic rubber outsole and OrthoLite\u00ae insole for cushioning, they feel as tranquil as they look. Try these sneakers for a peaceful take on the neutral trend.", "name": "Chuck Taylor All Star Botanical Neutrals High Top", "price": "CAD $70.00"}
{"description": "CHUCK 70. The classic we all know and love, revamped with premium elements. In the 1970s, Converse made one of the most popular shoes in the basketball game. Today, we pay homage to the legendary sneaker by obsessing over the details that made the shoe best in class - such as sidewall stitching and a higher rubber midsole. And with a varnished outsole and added OrthoLite\u00ae cushioning, the new Chuck 70 lets you hit the streets in both style and comfort.", "name": "Chuck 70 Equinox Low Top", "price": "CAD $105.00"}
{"description": "OLD SCHOOL STYLE, NEW SCHOOL MOVES. The One Star hits back with a bright, bold take on the vintage suede. Throwback details include premium hairy suede and a varnished midsole with pinstripes. Old school style meets new school technology, with OrthoLite\u00ae insole for cushioning to keep your feet feeling fresh.", "name": "One Star Vintage Suede Low Top", "price": "CAD $100.00"}
{"description": "CLASSIC KICKS, FRESH COLOURS. The Chuck Taylor All Star Low Top sneaker is always a favourite, but have you seen these colours? They\u2019re fresh for the season and ready to be rocked. With a durable canvas upper, rubber sole and Smart Foam sock liner for cushioning, these hot-coloured kicks won\u2019t be around for long.", "name": "Chuck Taylor All Star Seasonal Colours Low Top", "price": "CAD $65.00"}
{"description": "The Chuck Taylor All Star is the most iconic sneaker in the world, recognized for its unmistakable silhouette and cultural authenticity. Born on the court but adopted by rebels, rockers, rappers, artists, dreamers, thinkers and originals, the Chuck Taylor All Star in Monochrome White or Black continues our tradition of celebrating personal style and individual self-expression.", "name": "Chuck Taylor All Star Mono Canvas High Top", "price": "CAD $70.00"}
{"description": "The Chuck Taylor All Star is the most iconic sneaker in the world, recognized for its unmistakable silhouette and cultural authenticity. Born on the court but adopted by rebels, rockers, rappers, artists, dreamers, thinkers and originals, the Chuck Taylor All Star in Monochrome White or Black continues our tradition of celebrating personal style and individual self-expression.", "name": "Chuck Taylor All Star Mono Canvas Low Top", "price": "CAD $65.00"}
{"description": "The Converse Chuck Taylor All Star is the one that started it all for Converse. When it comes to sneakers, there\u2019s nothing more pure than a canvas upper and a vulcanized rubber sole. This is the sneaker that spawned countless imitators, with its star-centered patch, rubber toe cap, toe bumper and striping.", "name": "Chuck Taylor All Star High Top", "price": "CAD $70.00"}
{"description": "DO YOU WANT TO PLAY? The new drop in Converse and JW Anderson\u2019s creative collaboration is a timeless exploration of colliding aesthetics and deconstructed textiles. Converse\u2019s iconic Chuck 70 silhouette is remodeled \u2013 the graphic JW Anderson monogram playfully reconfigured through tectonic wordplay \u2013 in the seasonal shade: rich royal red. This is collaboration in its purest form, fiercely contemporary and totally timeless.", "name": "Converse x JW Anderson Chuck 70 Grid High Top", "price": "CAD $160.00"}
{"description": "ART IS FOR WEARING. Toy, a sculptural tribute to colour and gloss, is the newest iteration of Converse and JW Anderson\u2019s dynamic partnership. High-shine patent leather, bold contrasting colourways and textural laces inspired by San Francisco\u2019s famous stucco combine in this radical new iteration of the classic Chuck \u201870, reimagined to shine a provocative light on the power of contemporary creative culture.", "name": "Converse x JW Anderson Chuck 70 Toy Low Top", "price": "CAD $190.00"}
{"description": "The classic we all know and love, revamped with premium elements. In the 1970s, Converse made one of the most popular shoes in the basketball game. Today, we pay homage to the legendary sneaker by obsessing over the details that made the shoe best in class - such as sidewall stitching and a higher rubber midsole. And with a varnished outsole and added OrthoLite cushioning, the new Chuck 70 lets you hit the streets in both style and comfort.", "name": "Chuck 70 Low Top", "price": "CAD $85.00"}
{"description": "Illegal Civilization, the Hollywood-based skate team, has teamed up with Converse to present their take on the iconic Jack Purcell Pro model shoes. Coming in a black and white colorway, this skate-focused design has a canvas upper with IC logo detailing at the heel and on the tongue. The Ortholite sockliner provides an ultra-comfortable fit built for all-day wear.", "name": "Converse x Illegal Civilization Jack Purcell Pro Low Top", "price": "CAD $90.00"}
{"description": "FUTURE NOW. Heritage and technology from sport, style and construction from the street. Welcome to the Converse Nexus x Nike Zoom Air, the first chapter in a series of new creations from Converse.", "name": "Converse Nexus x Nike Zoom Air Low Top", "price": "CAD $150.00"}
{"description": "The One Star Pro from Converse has been reimagined as a collaborative design with Illegal Civilization, the up-and-coming skate team from Hollywood, California. The leather upper comes in an almost-white violet colorway and features Converse and IC logo detailing at the sidewalls, outsole and tongue. The One Star Pros come with a lace-up closure as well as an Ortholite + Zoom Air insole for the best in impact support.", "name": "Converse x Illegal Civilization One Star Low Top", "price": "CAD $100.00"}
{"description": "BOLD LOOK, EXCEPTIONAL COMFORT.", "name": "Men's Wrap Around Long Sleeve T-Shirt", "price": "CAD $40.00"}
{"description": "THE COLOUR-BLOCK RENAISSANCE", "name": "Men's Colorblock Crew Sweatshirt", "price": "CAD $80.00"}
{"description": "COURT-INSPIRED STYLE", "name": "Men's Basketball Jersey", "price": "CAD $75.00"}
{"description": "STAR CHEVRON TEE", "name": "Men's Seasonal Star Chevron T-Shirt", "price": "CAD $30.00"}
{"description": "ESSENTIAL COMFORT", "name": "Men's Essentials Graphic T-Shirt", "price": "CAD $40.00"}
{"description": "ESSENTIAL COMFORT", "name": "Men's Essentials Graphic Crew Sweatshirt", "price": "CAD $75.00"}
{"description": "ESSENTIAL HOODIE", "name": "Men's Essentials Graphic Pullover Hoodie", "price": "CAD $80.00"}
{"description": "SOCCER JERSEY STYLING", "name": "Men's Mixed Media T-Shirt", "price": "CAD $55.00"}
{"description": "BOLD LOOK, EXCEPTIONAL COMFORT.", "name": "Men's Cross Body Graphic T-Shirt", "price": "CAD $30.00"}
{"description": "A little bit country, a little bit punk rock.", "name": "Converse x Miley Cyrus Chuck Taylor All Star Low Top", "price": "CAD $85.00"}
{"description": "SUMMERTIME FUN. Feel the summer vibes with the Converse Flamingo Tee. This cotton, classic fit tee is all about bringing the fun, so throw it on and enjoy the season.", "name": "Men's Flamingo T-Shirt", "price": "CAD $35.00"}
{"description": "CLASSIC TRACK JACKET. The traditional track zip silhouette gets a modern update with the Converse Star Chevron Track Jacket. Take a close look and check out the details like the Star Chevron woven trim on the sleeves, zippered front pockets and unique back neck tape. Zip it up and go for speed.", "name": "Men's Star Chevron Track Jacket", "price": "CAD $100.00"}
{"description": "Converse Pride x Miley Cyrus Pullover Hoodie", "name": "Converse Pride x Miley Cyrus Pullover Hoodie", "price": "CAD $110.00"}
{"description": "STAR CHEVRON HOODIE", "name": "Men's Star Chevron Graphic Pullover Hoodie", "price": "CAD $80.00"}
{"description": "The iconic Thunderbolt silhouette gets a modern update with this collaborative design from Converse, the world-renowned shoe brand, and Illegal Civilization, the up-and-coming Hollywood-based shoe brand. These white leather shoes feature orange logo detailing at the sidewalls and outsole for a refreshing look while the EVA midsole provides a supportive fit for all-day comfort.", "name": "Converse x Illegal Civilization Thunderbolt Low Top", "price": "CAD $110.00"}
{"description": "CLASSIC LONG SLEEVE TEE", "name": "Men's Star Chevron Wordmark Long Sleeve T-Shirt", "price": "CAD $40.00"}
{"description": "The Converse Chuck Taylor All Star is the one that started it all for Converse. When it comes to sneakers, there\u2019s nothing more pure than a canvas upper and a vulcanized rubber sole. This is the sneaker that spawned countless imitators, with its rubber toe cap, toe bumper and striping.", "name": "Chuck Taylor All Star Low Top", "price": "CAD $65.00"}
{"description": "LAID BACK PULLOVER HOODIE. Feel the softness of French Terry in the Converse Essentials Lightweight Graphic Pullover Hoodie. Featuring a bold rubber-printed brand graphic, this hoodie is built to look tough and feel soft. Details like rubber draw cord trims, and a hidden media pocket for phone storage make this sweatshirt comfortable and functional.", "name": "Men's Essentials Lightweight Graphic Pullover Hoodie", "price": "CAD $100.00"}
{"description": "CLASSIC KICKS, FRESH COLOURS. The Chuck Taylor All Star high top sneaker is always a favourite, but have you seen these colours? They\u2019re fresh for the season and ready to be rocked. With a durable canvas upper, iconic Chuck Taylor patch, rubber sole and Smart Foam sock liner for cushioning, these hot-coloured kicks won\u2019t be around for long.", "name": "Chuck Taylor All Star Seasonal Colours High Top", "price": "CAD $70.00"}
{"description": "GOLF le FLEUR* presents florals for spring. Groundbreaking.", "name": "GOLF le FLEUR* T-Shirt", "price": "CAD $50.00"}
{"description": "SKATE TEAM APPROVED. PURE COTTON COMFORT. The Converse CONS Purple 5.1 Men's Long Sleeve T-Shirt is a premium offering celebrating Converse Skateboarding\u2019s first full-length skate film, PURPLE (May 2018).", "name": "CONS Purple Long Sleeve T-Shirt", "price": "CAD $40.00"}
{"description": "SKATE TEAM APPROVED. PURE COTTON COMFORT. The Converse CONS Purple 5.1 Men's T-Shirt is a premium offering celebrating Converse Skateboarding\u2019s first full-length skate film, PURPLE (May 2018).", "name": "CONS Purple T-Shirt", "price": "CAD $35.00"}
{"description": "PALM PRINT SKULL TEE", "name": "Men's Palm Print Skull T-Shirt", "price": "CAD $35.00"}
{"description": "A BOLD, CONTEMPORARY TEE. Go for a bold look with the Converse Star Chevron Tri colour tee. Constructed with comfortable cotton and a classic fit, this shirt is perfect for pairing with a pair of jeans for a day out with friends.", "name": "Men's Star Chevron Tri-Colour T-Shirt", "price": "CAD $30.00"}
{"description": "MEANT FOR YOUR PERSONAL STYLE. Kick back in the Converse Diamond Arch tee, featuring a comfortable classic fit silhouette and seasonal Star Chevron graphic on the left chest and back. It\u2019s a simple look that invites you to show off your own personal style.", "name": "Men's Diamond Arch T-Shirt", "price": "CAD $35.00"}
{"description": "COOL ENOUGH FOR SCHOOL. When you\u2019re thinking about what your kid needs for back to school, the Chuck Taylor All Star Street has got to make the list. A fashion essential, these comfortable kicks feature the fall\u2019s best colours, an elastic gore tongue for easy on and off, and a non-marking rubber outsole for traction. With small touches like a screen-printed medial patch, a Smart Foam with canvas sockliner, and medial eyelets for airflow, these are the sneakers that can stand up to even the longest of school days.", "name": "Chuck Taylor All Star Street Fall Uniform Mid Little/Big Kids", "price": "CAD $55.00"}
{"description": "The Converse Chuck Patch Men's T-Shirt is made with ultra-soft cotton for everyday comfort.", "name": "Men's Chuck Patch T-Shirt", "price": "CAD $30.00"}
{"description": "IT'S A CELEBRATION! Every day is a celebration with the Chuck Taylor All Star high top birthday confetti sneakers. The canvas upper features screen printed confetti with metallic foil for extra shine. The celebration continues with a screen printed medial patch, medial eyelets and a Smart Foam sockliner. Take the party to school, to the movies, or even to a party. It\u2019s fun that can\u2019t be matched.", "name": "Chuck Taylor All Star Confetti High Top Little/Big Kids", "price": "CAD $60.00"}
{"description": "IT'S A CELEBRATION! Every day is a celebration with the Chuck Taylor All Star low top birthday confetti sneakers. The canvas upper features screen printed confetti with metallic foil for extra shine. The celebration continues with medial eyelets and a Smart Foam sockliner. Take the party to school, to the movies, or even to a party. It\u2019s fun that can\u2019t be matched.", "name": "Chuck Taylor All Star Confetti Low Top Little/Big Kids", "price": "CAD $55.00"}
{"description": "COMFORT AND METALLIC FUN. The Chuck Taylor All Star Pull Zip is an absolute essential for the school year. These kicks feature a unique glam textile upper with metallic heelstay for additional sparkle, a zig-zag lace loop and zipper pull for easy to get on and off. It also has a fun debossed medial patch with metallic screenprint detail for an added touch. And when it comes to comfort, it\u2019s got you covered with a non-marking rubber outsole and Smart Foam with canvas sockliner.", "name": "Chuck Taylor All Star Pull-Zip High Top Little/Big Kids", "price": "CAD $65.00"}
{"description": "RECESS-INSPIRED FASHION. Because recess is always on every student\u2019s mind, the Chuck Taylor All Star Maddie will make sure she\u2019s totally ready when the time comes. Inspired by chalk art, the two-colour knit upper features muted pastel colours and a metallic woven tongue label for a fun look. The gored tongue is perfect for easy on and off when she's ready to roll. Also, the non-marking sole is perfect for playtime grip while the Smart Foam with canvas sockliner will keep her comfortable as she runs with her friends. Recess just went from fun to fashionable.", "name": "Chuck Taylor All Star Maddie Low Top Little/Big Kids", "price": "CAD $55.00"}
{"description": "THE SEASON\u2019S FINEST. Say hello to the bold colours of the season with the Chuck Taylor All Star high top sneaker. The durable canvas upper and non-marking sole for traction are key components when it comes to kicks that can keep up. The screen-printed medial patch and Smart Foam insole for cushioning are also vital for style and comfort. These kicks will always be classic, but your kid can make them unique by bringing their own style.", "name": "Chuck Taylor All Star Seasonal Colours High Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "CLASSIC AND COMFY. There's no stopping the iconic style of the Chuck Taylor All Star oxford sneaker. Made with amped up seasonal colours, these kicks sport a durable canvas upper, woven tongue label, non-marking rubber sole and medial eyelets for optimal airflow. Inside, things are as comfy as ever with the Smart Foam insole for cushioning.", "name": "Chuck Taylor All Star Seasonal Colours Low Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "Scaled back in size for little movers and shakers, the Converse Chuck Taylor All Star stay true to the iconic original with time-tested design lines and a comfortable canvas upper.", "name": "Chuck Taylor All Star High Top Infant/Toddler", "price": "CAD $40.00"}
{"description": "Scaled back in size for the next generation of original thinkers, rockers and artists, this Converse Chuck Taylor All Star remains true to the iconic original with classic details on a comfortable canvas upper.", "name": "Chuck Taylor All Star Low Top Infant/Toddler", "price": "CAD $40.00"}
{"description": "Scaled back in size for the next generation of original thinkers, rockers and artists, this Converse Chuck Taylor All Star remains true to the iconic original with classic details on a comfortable canvas upper.", "name": "Chuck Taylor All Star High Top Little/Big Kids", "price": "CAD $45.00"}
{"description": "IT'S A CELEBRATION! Every day is a celebration with the Chuck Taylor All Star Madison Low Top birthday confetti sneakers. The canvas upper features screen printed confetti with metallic foil for extra shine. The celebration continues with medial eyelets and a Smart Foam sockliner. Take the party to school, to the movies, or even to a party. It\u2019s fun that can\u2019t be matched.", "name": "Chuck Taylor All Star Madison Confetti Low Top Little/Big Kids", "price": "CAD $60.00"}
{"description": "CAN GO FAST. OR NOT.", "name": "Men's Star Chevron Track Pant", "price": "CAD $90.00"}
{"description": "COOL ENOUGH FOR SCHOOL. When you\u2019re thinking about what your kid needs for back to school, the Chuck Taylor All Star Street has got to make the list. A fashion essential, these comfortable kicks feature the fall\u2019s best colours, an elastic gore tongue for easy on and off, and a non-marking rubber outsole for traction. With small touches like a screen-printed medial patch, a Smart Foam with canvas sockliner, and aluminum eyelets, these are the sneakers that can stand up to even the longest of school days.", "name": "Chuck Taylor All Star Street Fall Uniform Mid Infant/Toddler", "price": "CAD $50.00"}
{"description": "SUPER SOFT GRAPHIC TEE. Feel the softness of Supima cotton in this Converse Essentials Graphic Tee. Featuring our Converse logo proudly, this tee is built for softness, quality and durability. Pick your favorite colour and style it your way.", "name": "Men's Essentials Supima Cotton Graphic T-Shirt", "price": "CAD $40.00"}
